config/routes.rb
Rails.application.routes.draw do
  # ver "/path", to: "controller#action"
  root to: "pages#home"
  get "/about", to: "pages#about"
  get "/contact", to: "pages#contact"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about 
  end

  def home 
  end

  def contact 
    @members = ["margarida", "claire", "miguel", "diogo", "toni"]
    
    search = params[:member]

    if search
      @members = @members.select { |member| member.start_with? search.downcase }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsIntro</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <h1>Our first rails app</h1>
    <%= yield %>
    <h3>Made with ❤️ at Le Wagon</h3>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About us 🚀</h1>

<%= link_to "Back to the Homepage", root_path %>

app/views/pages/contact.html.erb
<h1>Contact us 📫</h1>
<p>We like to receive messages!</p>

<% current_time = Time.now %>
<p>The current time is: <%= current_time %></p>

<form action="/contact" method="get">
  <input type="text" name="member" 
  value="<%= params[:member] %>"
  placehoder="Who are you looking for?">
  <input type="submit">
</form>

<h3>Meet our team members:</h3>
<ol>
  <% @members.each do |member| %>
  <li><%= member.capitalize %></li>
  <% end %>
</ol>

<%= link_to "Back to the Homepage", root_path %>

app/views/pages/home.html.erb
<h1>Homepage 🏡</h1>

<%= link_to "Contact Us", contact_path %>